CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE episodic_memory (
    -- Unique identifier for this specific memory record
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    
    -- Crucial for Row Level Security (RLS) and multi-tenancy
    user_id UUID NOT NULL, 
    
    -- Links the memory back to the specific chat session
    thread_id UUID NOT NULL, 
    
    -- The actual narrative summary generated by your background worker
    summary TEXT NOT NULL, 
    
    -- The vector representation of the 'summary' (assuming OpenAI's 1536 dims)
    embedding vector(1536) NOT NULL, 
    
    -- For an e-commerce competition, this is highly valuable for agent routing
    -- e.g., 'purchased', 'cart_abandoned', 'inquiry_resolved'
    outcome TEXT, 
    
    -- Catch-all for extra tags or specific tool calls made during the episode
    metadata JSONB DEFAULT '{}'::jsonb, 
    
    -- The most important field for episodic retrieval: Absolute Time
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- Essential index to make vector similarity searches fast
CREATE INDEX ON episodic_memory USING hnsw (embedding vector_cosine_ops);

-- Essential index to make time-based filtering fast
CREATE INDEX idx_episodic_user_time ON episodic_memory (user_id, created_at DESC);
